; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_=music_data_
.endif

music_data_:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : SMB Complete - Menu
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word 307,256

.export music_data_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env13,@env8,@env9,@env0 ; 00 : hh
	.word @env6,@env10,@env9,@env0 ; 01 : kick
	.word @env15,@env12,@env9,@env0 ; 02 : snare
	.word @env16,@env8,@env11,@env0 ; 03 : New instrument
	.word @env1,@env8,@env3,@env0 ; 04 : New instrument 5

@instruments_exp:
	.word @env4, @env8, @env0 ; 00 : New instrument 4
	.word @env14, @env8
	.byte $00, $03
	.word 1000
	.byte $00, $00
	.word @env2, @env8, @env0 ; 01 : New instrument 2
	.word @env14, @env8
	.byte $00, $03
	.word 1000
	.byte $00, $00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cf,$ce,$cd,$cc,$cb,$ca,$ca,$c9,$02,$c8,$c8,$c7,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$c1,$c0,$00,$18
@env2:
	.byte $00,$cf,$ce,$cc,$c9,$cd,$cb,$c9,$c7,$c5,$c3,$c0,$00,$0b
@env3:
	.byte $c1,$c2,$00,$01
@env4:
	.byte $00,$ca,$cc,$cd,$00,$03
@env5:
	.byte $00,$c0,$bf,$02,$c0,$c1,$c1,$c1,$00,$01
@env6:
	.byte $00,$cf,$cc,$c7,$c2,$c0,$00,$05
@env7:
	.byte $00,$c0,$bf,$bf,$be,$02,$bf,$bf,$c0,$c1,$c1,$c2,$02,$c1,$c1,$00,$01
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $c0,$02,$bf,$00,$02
@env11:
	.byte $c0,$c1,$00,$01
@env12:
	.byte $c0,$c7,$00,$01
@env13:
	.byte $00,$cf,$cb,$c8,$c0,$00,$04
@env14:
	.byte $c8,$7f,$00,$00
@env15:
	.byte $00,$ce,$cd,$cc,$cb,$ca,$c8,$c4,$c1,$c0,$00,$09
@env16:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$c9,$c8,$c7,$c6,$c5,$00,$0a

@samples:

@song0ch0:
	.byte $46, $06
@song0ch0loop:
	.byte $7b
@song0ref5:
	.byte $4e, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $1e, $8d, $49, .lobyte(@env7), .hibyte(@env7), $8f, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $86, $20, $8d, $49, .lobyte(@env7), .hibyte(@env7), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $86, $21, $8d, $49, .lobyte(@env7), .hibyte(@env7), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $23, $8d, $49
	.byte .lobyte(@env7), .hibyte(@env7), $8f
	.byte $41, $0c
	.word @song0ref5
	.byte $41, $0c
	.word @song0ref5
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $1e, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $23, $85, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $21, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1c, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $1a, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1f, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1d, $85
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $18, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1c, $8d, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $9f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $83, $7a, $51, $fa, $00, $88, $2f, $87, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7b
@song0ref134:
	.byte $4e, $ff, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $27, $8d, $49, .lobyte(@env7), .hibyte(@env7), $8f, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $86, $29, $8d, $49, .lobyte(@env7), .hibyte(@env7), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $86, $2a, $8d, $49, .lobyte(@env7), .hibyte(@env7), $8f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $2a, $8d, $49
	.byte .lobyte(@env7), .hibyte(@env7), $8f
	.byte $41, $0c
	.word @song0ref134
	.byte $41, $0c
	.word @song0ref134
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $27, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2c, $85, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $25, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2a, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $23, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $28, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $21, $85
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $26, $85, $49, .lobyte(@env0), .hibyte(@env0), $4a, $25, $8d, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $9f, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $85, $7a, $51, $fa, $10, $88, $3b, $85, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $86
@song0ref263:
	.byte $17, $85, $00, $81, $17, $81, $00, $81, $17, $81, $23, $81, $17, $81, $19, $85, $00, $81, $19, $81, $00, $81, $19, $81
	.byte $25, $81, $19, $81, $1a, $85, $00, $81, $1a, $81, $00, $81, $1a, $81, $26, $81, $1a, $81, $1c, $85, $00, $81, $1c, $81
	.byte $00, $81, $1c, $81, $28, $81, $1c, $81
	.byte $41, $38
	.word @song0ref263
	.byte $41, $38
	.word @song0ref263
	.byte $17, $85, $1c, $85, $1a, $85, $1f, $85, $13, $85, $18, $85, $16, $85, $1b, $85, $15, $85, $00, $81, $15, $81, $00, $81
	.byte $15, $81, $21, $81, $15, $81, $00, $81, $15, $81, $00, $81, $15, $81, $00, $8d, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref369:
	.byte $7d, $82, $16, $81, $78, $80, $20, $81, $7b, $20, $81, $7d, $82, $16, $81, $78, $80, $20, $81, $7b, $20, $81, $7c, $84
	.byte $18, $81, $78, $80, $20, $81
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $41, $10
	.word @song0ref369
	.byte $7d, $82, $16
@song0ref435:
	.byte $81, $78, $80, $20, $7b, $20, $7d, $82, $16, $81, $78, $80, $20, $7b, $20, $7d, $82, $16, $81, $78, $80, $20, $7b, $20
	.byte $7c, $84, $18
	.byte $41, $0b
	.word @song0ref435
	.byte $7d, $82, $16, $81, $78, $80, $20, $7b, $20, $7c, $84, $18, $81, $78, $80, $20, $7b, $20
	.byte $41, $10
	.word @song0ref369
	.byte $41, $09
	.word @song0ref369
	.byte $8d, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff, $ff, $ff, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $7c, $82
@song0ref504:
	.byte $2a, $81, $2f, $81, $33, $81, $2a, $85, $2f, $81, $33, $81, $2a, $81, $2c, $81, $31, $81, $35, $81, $2c, $85, $31, $81
	.byte $35, $81, $2c, $81, $2d, $81, $32, $81, $36, $81, $2d, $85, $32, $81, $36, $81, $2d, $81, $2f, $81, $34, $81, $36, $81
	.byte $2f, $85, $34, $81, $36, $81, $2f, $81
	.byte $41, $38
	.word @song0ref504
	.byte $41, $38
	.word @song0ref504
	.byte $2a, $81, $2f, $81, $2f, $81, $34, $81, $28, $81, $2d, $81, $2d, $81, $32, $81, $26, $81, $2b, $81, $2b, $81, $30, $81
	.byte $24, $81, $29, $81, $29, $81, $2e, $81, $25, $81, $2a, $81, $2c, $81, $31, $85, $2c, $81, $2a, $81, $25, $81, $25, $81
	.byte $2a, $81, $2c, $81, $31, $91, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $00, $fd
@song0ref626:
	.byte $7d
@song0ref627:
	.byte $80, $33, $81, $34, $81, $36, $81, $3b, $81, $49, .lobyte(@env5), .hibyte(@env5), $83, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $36, $81, $34, $81, $33, $85, $49, .lobyte(@env5), .hibyte(@env5), $8b, $78, $81, $74, $81, $70, $83, $7d
@song0ref662:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $33, $81, $31, $81, $36, $81, $34, $81, $32, $81, $2f, $81, $78, $81
	.byte $74, $81, $7d
@song0ref684:
	.byte $2f, $81, $36, $81, $34, $81, $49, .lobyte(@env5), .hibyte(@env5), $83, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80
	.byte $32, $81, $31, $81, $2f, $81, $31, $81, $49, .lobyte(@env5), .hibyte(@env5), $83, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $81, $78, $81, $74, $81, $70, $81
	.byte $41, $35
	.word @song0ref626
	.byte $00, $fd, $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $00, $fd, $70, $83, $7a, $4e, $ff
	.byte $41, $0f
	.word @song0ref627
	.byte $49, .lobyte(@env5), .hibyte(@env5), $8d, $70, $85, $7a
	.byte $41, $0c
	.word @song0ref662
	.byte $74, $81, $70, $81, $7a
	.byte $41, $11
	.word @song0ref684
	.byte $74, $81, $70, $83, $7a, $4e, $ff
	.byte $41, $0f
	.word @song0ref627
	.byte $49, .lobyte(@env5), .hibyte(@env5), $8d, $70, $85, $7a
	.byte $41, $0c
	.word @song0ref662
	.byte $74, $81, $70, $81, $7a
	.byte $41, $11
	.word @song0ref684
	.byte $74, $81, $00, $fd, $42
	.word @song0ch7loop
