; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_smb_complete_menu:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : SMB Complete - Menu
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.word 307,256

.export music_data_smb_complete_menu
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env13,@env8,@env9,@env0 ; 00 : hh
	.word @env6,@env10,@env9,@env0 ; 01 : kick
	.word @env15,@env12,@env9,@env0 ; 02 : snare
	.word @env16,@env8,@env11,@env0 ; 03 : New instrument
	.word @env1,@env8,@env3,@env0 ; 04 : New instrument 5

@instruments_exp:
	.word @env4, @env8, @env0 ; 00 : New instrument 4
	.word @env14, @env8
	.byte $00, $03
	.word 1000
	.byte $00, $00
	.word @env2, @env8, @env0 ; 01 : New instrument 2
	.word @env14, @env8
	.byte $00, $03
	.word 1000
	.byte $00, $00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cf,$ce,$cd,$cc,$cb,$ca,$ca,$c9,$02,$c8,$c8,$c7,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$c1,$c0,$00,$18
@env2:
	.byte $00,$cf,$ce,$cc,$c9,$cd,$cb,$c9,$c7,$c5,$c3,$c0,$00,$0b
@env3:
	.byte $c1,$c2,$00,$01
@env4:
	.byte $00,$ca,$cc,$cd,$00,$03
@env5:
	.byte $00,$c0,$bf,$02,$c0,$c1,$c1,$c1,$00,$01
@env6:
	.byte $00,$cf,$cc,$c7,$c2,$c0,$00,$05
@env7:
	.byte $00,$c0,$bf,$bf,$be,$02,$bf,$bf,$c0,$c1,$c1,$c2,$02,$c1,$c1,$00,$01
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $c0,$02,$bf,$00,$02
@env11:
	.byte $c0,$c1,$00,$01
@env12:
	.byte $c0,$c7,$00,$01
@env13:
	.byte $00,$cf,$cb,$c8,$c0,$00,$04
@env14:
	.byte $c8,$7f,$00,$00
@env15:
	.byte $00,$ce,$cd,$cc,$cb,$ca,$c8,$c4,$c1,$c0,$00,$09
@env16:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$c9,$c8,$c7,$c6,$c5,$00,$0a

@samples:

@song0ch0:
	.byte $46, $01
@song0ch0loop:
	.byte $7b
@song0ref5:
	.byte $4e, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $1e, $dd, $49, .lobyte(@env7), .hibyte(@env7), $df, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $86, $20, $dd, $49, .lobyte(@env7), .hibyte(@env7), $df, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $86, $21, $dd, $49, .lobyte(@env7), .hibyte(@env7), $df, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $23, $dd, $49
	.byte .lobyte(@env7), .hibyte(@env7), $df
	.byte $41, $0c
	.word @song0ref5
	.byte $41, $0c
	.word @song0ref5
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $1e, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $23, $ad, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $21, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1c, $ad, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $1a, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1f, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1d, $ad
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $18, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $1c, $dd, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $ff, $bf, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $a1, $7a, $51, $fa, $00, $88, $2f, $b9, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7b
@song0ref135:
	.byte $4e, $ff, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $27, $dd, $49, .lobyte(@env7), .hibyte(@env7), $df, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $86, $29, $dd, $49, .lobyte(@env7), .hibyte(@env7), $df, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $86, $2a, $dd, $49, .lobyte(@env7), .hibyte(@env7), $df, $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $2a, $dd, $49
	.byte .lobyte(@env7), .hibyte(@env7), $df
	.byte $41, $0c
	.word @song0ref135
	.byte $41, $0c
	.word @song0ref135
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $86, $27, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2c, $ad, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $25, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $2a, $ad, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $23, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $28, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $21, $ad
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $26, $ad, $49, .lobyte(@env0), .hibyte(@env0), $4a, $25, $dd, $49, .lobyte(@env7)
	.byte .hibyte(@env7), $ff, $bf, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $ad, $7a, $51, $fa, $10, $88, $3b, $ad, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $86
@song0ref265:
	.byte $17, $ad, $00, $95, $17, $95, $00, $95, $17, $95, $23, $95, $17, $95, $19, $ad, $00, $95, $19, $95, $00, $95, $19, $95
	.byte $25, $95, $19, $95, $1a, $ad, $00, $95, $1a, $95, $00, $95, $1a, $95, $26, $95, $1a, $95, $1c, $ad, $00, $95, $1c, $95
	.byte $00, $95, $1c, $95, $28, $95, $1c, $95
	.byte $41, $38
	.word @song0ref265
	.byte $41, $38
	.word @song0ref265
	.byte $17, $ad, $1c, $ad, $1a, $ad, $1f, $ad, $13, $ad, $18, $ad, $16, $ad, $1b, $ad, $15, $ad, $00, $95, $15, $95, $00, $95
	.byte $15, $95, $21, $95, $15, $95, $00, $95, $15, $95, $00, $95, $15, $95, $00, $dd, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref371:
	.byte $7d, $82, $16, $95, $78, $80, $20, $95, $7b, $20, $95, $7d, $82, $16, $95, $78, $80, $20, $95, $7b, $20, $95, $7c, $84
	.byte $18, $95, $78, $80, $20, $95
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $41, $10
	.word @song0ref371
	.byte $7d, $82, $16
@song0ref437:
	.byte $95, $78, $80, $20, $89, $7b, $20, $89, $7d, $82, $16, $95, $78, $80, $20, $89, $7b, $20, $89, $7d, $82, $16, $95, $78
	.byte $80, $20, $89, $7b, $20, $89, $7c, $84, $18
	.byte $41, $11
	.word @song0ref437
	.byte $7d, $82, $16, $95, $78, $80, $20, $89, $7b, $20, $89, $7c, $84, $18, $95, $78, $80, $20, $89, $7b, $20, $89
	.byte $41, $10
	.word @song0ref371
	.byte $41, $09
	.word @song0ref371
	.byte $dd, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref506:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $09
	.word @song0ref506
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $7c, $82
@song0ref530:
	.byte $2a, $95, $2f, $95, $33, $95, $2a, $ad, $2f, $95, $33, $95, $2a, $95, $2c, $95, $31, $95, $35, $95, $2c, $ad, $31, $95
	.byte $35, $95, $2c, $95, $2d, $95, $32, $95, $36, $95, $2d, $ad, $32, $95, $36, $95, $2d, $95, $2f, $95, $34, $95, $36, $95
	.byte $2f, $ad, $34, $95, $36, $95, $2f, $95
	.byte $41, $38
	.word @song0ref530
	.byte $41, $38
	.word @song0ref530
	.byte $2a, $95, $2f, $95, $2f, $95, $34, $95, $28, $95, $2d, $95, $2d, $95, $32, $95, $26, $95, $2b, $95, $2b, $95, $30, $95
	.byte $24, $95, $29, $95, $29, $95, $2e, $95, $25, $95, $2a, $95, $2c, $95, $31, $ad, $2c, $95, $2a, $95, $25, $95, $25, $95
	.byte $2a, $95, $2c, $95, $31, $f5, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $00, $ff, $ff, $ff, $ff, $ff, $fd
@song0ref657:
	.byte $7d
@song0ref658:
	.byte $80, $33, $95, $34, $95, $36, $95, $3b, $95, $49, .lobyte(@env5), .hibyte(@env5), $97, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $80, $36, $95, $34, $95, $33, $ad, $49, .lobyte(@env5), .hibyte(@env5), $c7, $78, $8b, $74, $8b, $70, $97, $7d
@song0ref693:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $80, $33, $95, $31, $95, $36, $95, $34, $95, $32, $95, $2f, $95, $78, $8b
	.byte $74, $8b, $7d
@song0ref715:
	.byte $2f, $95, $36, $95, $34, $95, $49, .lobyte(@env5), .hibyte(@env5), $97, $49, .lobyte(@env0), .hibyte(@env0), $4a, $80
	.byte $32, $95, $31, $95, $2f, $95, $31, $95, $49, .lobyte(@env5), .hibyte(@env5), $97, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $8b, $78, $8b, $74, $8b, $70, $8b
	.byte $41, $35
	.word @song0ref657
	.byte $00, $ff, $ff, $ff, $ff, $ff, $fd, $42
	.word @song0ch6loop
@song0ch7:
@song0ch7loop:
	.byte $00, $ff, $ff, $ff, $ff, $ff, $fd, $70, $97, $7a, $4e, $ff
	.byte $41, $0f
	.word @song0ref658
	.byte $49, .lobyte(@env5), .hibyte(@env5), $d3, $70, $a3, $7a
	.byte $41, $0c
	.word @song0ref693
	.byte $74, $8b, $70, $8b, $7a
	.byte $41, $11
	.word @song0ref715
	.byte $74, $8b, $70, $97, $7a, $4e, $ff
	.byte $41, $0f
	.word @song0ref658
	.byte $49, .lobyte(@env5), .hibyte(@env5), $d3, $70, $a3, $7a
	.byte $41, $0c
	.word @song0ref693
	.byte $74, $8b, $70, $8b, $7a
	.byte $41, $11
	.word @song0ref715
	.byte $74, $8b, $00, $ff, $ff, $ff, $ff, $ff, $fd, $42
	.word @song0ch7loop
